version: '3'

services:
  fe1:
    image: jdk11-starrocks-fe:3.2.6
    container_name: fe1
    ports:
      - "9031:9030"
      - "8031:8030"
    extra_hosts:
      - "node136:192.168.2.136"
    command: fe
    volumes:
      - ./fe1/meta:/opt/starrocks/fe/meta
      - ./fe1/logs:/opt/starrocks/fe/log

  be1:
    image: jdk11-starrocks-be:3.2.6
    container_name: be1
    command: be
#    ports:
#      - "9040:9040"
#      - "9060:9060"
    extra_hosts:
      - "node136:192.168.2.136"
    volumes:
      - ./be1/storage:/opt/starrocks/be/storage
      - ./be1/logs:/opt/starrocks/be/log
    depends_on:
      - fe1
